#pragma kernel CSMain
#include "Math.hlsl"

RWTexture2D<float4> input;
RWTexture2D<float> cloudDepthMap;
RWTexture2D<float4> transmittanceMap;

float2 jitterIndex;

Texture2D<float4> weatherMap;
SamplerState sampler_weatherMap;

Texture3D<float4> shapeNoise;
SamplerState sampler_shapeNoise;

Texture3D<float4> detailNoise;
SamplerState sampler_detailNoise;

Texture2D<float4> blueNoise;
SamplerState sampler_blueNoise;

float density;
float threshold;
float scale;
float detailScale;
float absorption;
float attenuationClamp;
float minimumAttenuationAmbient;
float outScatteringAmbient;

float sunIntensity;
float sunIntensityRadius;
float inScatter;
float outScatter;
float scatterLerp;

float2 shapeOffset;
float2 detailOffset;

float atmosphericBlending;
float2 imageSize;

float cloudStart;
float cloudEnd;

//Unity stuff
float3 startingCameraPosition;
float3 mainLightDirection;
float4 mainLightColour;
float4 ambient;
float4x4 unityCameraInverseProjection;
float4x4 unityCameraToWorld;

float SampleDensity(float3 position, float percentHeight)
{
    float4 noiseSample = shapeNoise.SampleLevel(sampler_shapeNoise,
        (position.xyz + float3(shapeOffset.x, 0, shapeOffset.y)) * scale, 0);
    
    float4 detailSample = detailNoise.SampleLevel(sampler_detailNoise,
        (position.xyz + float3(detailOffset.x, 0, detailOffset.y)) * detailScale, 0);
    
    //float4 weatherMapSample = weatherMap.SampleLevel(sampler_weatherMap, localCoordinates.xz, 0);
        
    float fbm = noiseSample.y * 0.625f + noiseSample.z * 0.25f + noiseSample.w * 0.125f;
    float finalShape = Remap(noiseSample.x, fbm - 1, 1, 0, 1);
        
    float detailFBM = detailSample.x * 0.625f + detailSample.y * 0.25f + detailSample.z * 0.125f;

    float detailNoiseModification = 0.35f * exp(-threshold * 0.75f) * lerp(detailFBM, 1 - detailFBM,
        clamp(percentHeight * 5.0f, 0, 1));
        
    //float cloudProbability = max(weatherMapSample.x, clamp(threshold - 0.5f, 0, 1) * weatherMapSample.y * 2);
    float shapeAltering = ShapeAlteringHeight(percentHeight, 1.0f);
    float densityAltering = DensityAlteringHeight(percentHeight, 1.0f, density);
        
    float finalSample = clamp(Remap(finalShape * shapeAltering, 1 - threshold,
        1, 0, 1), 0, 1);
    float finalDensity = clamp(Remap(finalSample, detailNoiseModification,
        1, 0, 1), 0, 1) * densityAltering;

    return max(finalDensity - 0.6f, 0);
}

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float2 imageUV = (id.xy * 4) / imageSize.xy;
    float3 viewVector = mul(unityCameraInverseProjection, float4(imageUV.xy * 2.0f - 1.0f, 0.0f, -1.0f)).xyz;
    viewVector = mul(unityCameraToWorld, float4(viewVector.x, viewVector.y, -viewVector.z, 0.0f)).xyz;

    int sunSteps = 3;
        
    float transmittance = 1;
    float radiance = 0;
    float distanceFade = 0;
    float atmosphereFadeDistance = 0;
    
    float highDetailStepSize = 0.2f;
    float lowDetailStepSize = 1.0f;

    float highDetailDistanceTravelled = 0.0f;
    float stepSize = lowDetailStepSize;

    float4 blueNoiseOffset = float4(0,0,0,0); //blueNoise.SampleLevel(sampler_blueNoise, imageUV, 0);
    float distanceTravelled = 0;

    float3 cameraPosition = startingCameraPosition;
    int stepsTaken = 0;
    float distanceLimit = cloudEnd - cloudStart;
    float lightingStepSize = 2.0f;

    float rayMidpointIntersect = dot(normalize(float3(0,0,4) - cameraPosition), viewVector);
    float rayMidpointSphereCenterDistance = length(float3(0,0,4) - (cameraPosition + viewVector * rayMidpointIntersect));
    float rayDstToEdge = sqrt(pow(cloudStart, 2) - pow(rayMidpointSphereCenterDistance, 2));
    
    float raySphereIntersect = length(cameraPosition) < cloudStart ?
        rayMidpointIntersect + rayDstToEdge : rayMidpointIntersect - rayDstToEdge;

    input[id.xy] = float4(rayMidpointSphereCenterDistance,rayMidpointSphereCenterDistance,rayMidpointSphereCenterDistance,0)/50.0f;
    
    // if(rayDstToEdge > cloudStart)
    // {
    //     input[id.xy] = float4(0,0,0,0);
    // }
    // else
    // {
    //     input[id.xy] = float4(1, 0, 0, 0);
    // }
    return;

    cameraPosition += viewVector * (blueNoiseOffset * stepSize * 2).xyz;
    while (distanceTravelled < distanceLimit)
    {
        float3 rayPosition = cameraPosition + viewVector * (distanceTravelled);
        float percentHeight = (rayPosition.y - cloudStart) / cloudEnd;
        float densityAtPoint = SampleDensity(rayPosition, percentHeight) * stepSize;

        distanceFade += length(cameraPosition - rayPosition) * transmittance;
        stepsTaken++;
            
        distanceTravelled += stepSize;
        if(stepSize == highDetailStepSize)
            highDetailDistanceTravelled += highDetailStepSize;
                
        if(densityAtPoint > 0.0f &&
            stepSize == lowDetailStepSize)
        {
            distanceTravelled -= stepSize * 2;
            stepSize = highDetailStepSize;
            highDetailDistanceTravelled = 0.0f;
            if(atmosphereFadeDistance == 0)
                atmosphereFadeDistance = length(startingCameraPosition - rayPosition);
            continue;
        }
        if (densityAtPoint <= 0.0f && highDetailDistanceTravelled > highDetailStepSize * 10.0f &&
            stepSize == highDetailStepSize)
        {
            stepSize = lowDetailStepSize;
            continue;
        }

        if(densityAtPoint <= 0)
            continue;
            
        float toSunDensity = 0.0f;
        for (int v = 0; v < sunSteps; v++)
        {
            rayPosition += mainLightDirection * lightingStepSize;
            float toSunPercentHeight = rayPosition.y / 500.0f;
            toSunDensity += SampleDensity(rayPosition, toSunPercentHeight) * lightingStepSize;

            if(toSunDensity >= 1.0f)
                break;
        }
            
        float shadow = clamp(exp(-toSunDensity), attenuationClamp, 1.0f);
        shadow = max(toSunDensity * minimumAttenuationAmbient, shadow);
        float outScattering = 1 - saturate(outScatteringAmbient * 2 *
                pow(abs(densityAtPoint * (1 - transmittance)),
                    Remap(percentHeight, 0.3f, 0.9f, 0.5, 1.0f))) *
            saturate(pow(abs(Remap(percentHeight, 0, 0.3f, 0.8f, 1.0f)), 0.8f));

        float dotAngle = dot(mainLightDirection, normalize(rayPosition - cameraPosition));
        float sunLocalIntensity = sunIntensity * pow(clamp(dotAngle, 0, 1), sunIntensityRadius);
        float anisotropicScattering = lerp(max(HenyeyGreenstein(dotAngle, inScatter), sunLocalIntensity),
                                           HenyeyGreenstein(dotAngle, -outScatter), scatterLerp);
                
        radiance += densityAtPoint * transmittance * outScattering * shadow;
        transmittance *= exp(-densityAtPoint * absorption);

        if(radiance >= 1.0f)
            break;
                
        if(transmittance <= 0.01f)
            break;
    }

    float attenuatedTransmittance = clamp(exp(-atmosphereFadeDistance / (atmosphericBlending * 100.0f)) *
        (1 - transmittance), 0, 1);
    attenuatedTransmittance = smoothstep(0, 1, attenuatedTransmittance);
    distanceFade/= distanceLimit;
    
    transmittanceMap[id.xy] = float4(imageUV.xy, 0, 0); //attenuatedTransmittance;
    cloudDepthMap[id.xy] = atmosphereFadeDistance;
    input[id.xy] = attenuatedTransmittance * mainLightColour * radiance + ambient * (1 - radiance);
}
