#pragma kernel CSMain
#pragma target 5

RWTexture3D<float4> output;
StructuredBuffer<float3> points;

int3 tiles;
int tileSize;

float4 channel;
float contribution;

int3 imageDimensions;

[numthreads(1, 1, 1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float closestDist = 1000000000.0f;

    int tileIndexX = id.x / tileSize;
    int tileIndexY = id.y / tileSize;
    int tileIndexZ = id.z / tileSize;
    
    for (int i = -1; i <= 1; i++)
    {
        uint xIndex = (uint)(tileIndexX + i + tiles.x) % tiles.x;
        float xOffset = ((float)(tileIndexX + i)/(float)tiles.x - (float)xIndex/(float)tiles.x) * tiles.x;

        for (int j = -1; j <= 1; j++)
        {
            uint yIndex = (uint)(tileIndexY + j + tiles.y) % tiles.y;
            float yOffset = ((float)(tileIndexY + j)/(float)tiles.y - (float)yIndex/(float)tiles.y) * tiles.y;

            for (int k = -1; k <= 1; k++)
            {
                uint zIndex = (uint)(tileIndexZ + k + tiles.z) % tiles.z;
                float zOffset = ((float)(tileIndexZ + k)/(float)tiles.z - (float)zIndex/(float)tiles.z) * tiles.z;
                
                int flattenedIndex = zIndex * tiles.x * tiles.y + yIndex * tiles.x + xIndex;

                float3 currentPoint = points[flattenedIndex] + float3(xOffset, yOffset, zOffset) * tileSize;

                float dist = pow(id.x - currentPoint.x, 2) + pow(id.y - currentPoint.y, 2) + pow(id.z - currentPoint.z, 2);
                if(closestDist > dist)
                    closestDist = dist;
            }
        }
    }

    //Theoretical max, in practice this is extremely rare
    float greatestDistance = (tileSize * tileSize) * 3.0f;
    
    output[id.xyz] += channel * (contribution * 0.5 - contribution * closestDist/greatestDistance);
}
